### ISSUE TITLE
multiple_adventure_crafting_materials()无效

### ISSUE THREAD

**Issue by zzyspace** [onemedicine/MultipleRarity#1]
702a 合约的 multiple_adventure_crafting_materials() 方法调用之后, 只花费了 0.008FTM, 没有做地牢任务.

**Comment by onemedicine** [comment]
> 首先调用rarity 合约中的approve为单个角色授权，下地牢前想要打赢boos获取材料应把角色属性点满，地牢同样也是每24小时只能打一次。
> 如何判断有没有更新地牢任务，可查询地牢副本合约：0x2A0F1cB17680161cF255348dDFDeE94ea8Ca196A 中的adventurers_log()，时间戳更新次日即为已刷该副本。
> 刚演示的交易：https://ftmscan.com/tx/0xfbe9e62cc6fda7bc8d1a0fc5d8951f77894cfc83c0f7a3aecda4f244d725c78c#eventlog，该笔交易中我输入两个角色[421794,422028]下副本，其中421794并未满足adventurers_log()记录的冷却时间1631540993，而422028则成功下副本但战败。

**Comment by zzyspace** [comment]
规则我都明白的，我使用的ID都符合副本条件。唯一和你描述不同的是我用的approveAll，这个有影响吗?

**Comment by onemedicine** [comment]
这就是关键了，在地牢和金币的合约中判断授权的方法如下：
```
    function _isApprovedOrOwner(uint _summoner) internal view returns (bool) {
        return rm.getApproved(_summoner) == msg.sender || rm.ownerOf(_summoner) == msg.sender;
    }
```
在rarity中判断授权的方法如下：
```
    function _isApprovedOrOwner(address spender, uint256 tokenId) internal view virtual returns (bool) {
        require(_exists(tokenId), "ERC721: operator query for nonexistent token");
        address owner = ERC721.ownerOf(tokenId);
        return (spender == owner || getApproved(tokenId) == spender || isApprovedForAll(owner, spender));
    }
```

由于地牢副本和金币合约未检查isApprovedForAll(owner, spender)，所以只能使用approve单个授权。

**Comment by zzyspace** [comment]
那只能一个一个地approve了是吗，那量大的话是比较难搞😅

**Comment by onemedicine** [comment]
确实，若无其他疑问我将关闭此issue。

**Comment by zzyspace** [comment]
谢谢
