### ISSUE TITLE
请教一些代码问题

### ISSUE THREAD

**Issue by grayguest** [onemedicine/MultipleRarity#2]
作者你好，我是个合约新手，我有一些疑问想请教，
1. 你写的constract我大概能看懂，interface那部分
```
interface rarity_crafting_materials {
    function adventure(uint _summoner) external returns (uint);
    
    function adventurers_log (uint _summoner) external pure returns (uint);
}
```
但是`function adventurers_log (uint _summoner) external pure returns (uint);`这个函数我在https://ftmscan.com/address/0x2A0F1cB17680161cF255348dDFDeE94ea8Ca196A#code
没找到实现呢，这是咋回事呢，是它之前有然后去掉了吗？合约我记得看文章说是部署之后只能destroy不能change的吧。

2. 这个项目中go代码是做什么用的，go代码没看懂，我不太懂go，能用其他语言比如python/js实现go代码要实现的功能吗？

**Comment by onemedicine** [comment]
public  修饰符的影响

```
mapping(uint => uint) public adventurers_log;
```
编译后ABI中也会默认形成一个接口
```
	{
		"inputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"name": "adventurers_log",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
```

**Comment by grayguest** [comment]
哦，明白了，那go代码是做什么的呢
